# Generated by Django 5.2.7 on 2025-10-16 21:46

import apps.rosstat_parser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название региона')),
                ('analytical_table', models.FileField(blank=True, null=True, upload_to=apps.rosstat_parser.models.region_upload_path, verbose_name='Файл аналитических таблиц региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
    ]
