# Generated by Django 5.2.7 on 2025-10-16 22:36

import apps.rosstat_parser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosstat_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='analytical_table',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=apps.rosstat_parser.models.region_upload_path, verbose_name='Файл аналитических таблиц региона'),
        ),
    ]
