# Generated by Django 5.2.7 on 2025-10-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosstat_parser', '0002_alter_region_analytical_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название региона'),
        ),
    ]
